batch_size: 256
epochs: 70
epochs_til_checkpoint: 5
expand: 0.01
experiment_name: table
hidden_num: 128
latent_dim: 128
logging_root: ./logs
loss_correct: 100.0
loss_grad_deform: 1
loss_grad_temp: 100.0
lr: 0.0001
max_points: 200000
model_type: sine
num_instances: 4000
on_surface_points: 4000
point_cloud_path: datasets/table/surface_pts_n_normal
steps_til_summary: 100
train_split: split/train/table.txt